[profile.ci]
verbosity = 4

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version="0.8.26"
auto_detect_solc = true # this shuld be ignored if solc_version is set
via_ir=true
remappings = [
  "solidstate/=lib/solidstate-solidity/contracts/", 
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options